### ISSUE TITLE
Error when hit "Play"

### ISSUE THREAD

**Issue by VrTech** [chromealex/ecs.example#1]
Using Unity 2019.4.10f1
Photon is already setup

![image](https://user-images.githubusercontent.com/19533090/94431509-95e31280-01bf-11eb-8961-b6d79622a6ae.png)

Is there a workaround?

**Comment by chromealex** [comment]
Yeah. You are using windows os, there is a bug in Generator.cs. You can
copy-paste it from the main repo.
Thanks;)
