### ISSUE TITLE
Rollbacks

### ISSUE THREAD

**Issue by echeg** [chromealex/ecs.example#2]
And where can you see information or an example of how rollbacks work?

From the diagram, I realized that the input (markers) is being resimulated. And there are some checkpoints.

But in order to make the correct resimulation it is necessary to resimulate all systems. How realistic is this in heavy logic?
For example, if our simulation can work maximum 100 times per second, and in runtime it works 30 times per second.
Then, having received the packet 0.5s ago, we must resimulate the last 15 ticks. 15 / (100-30) = 0.214s is about 6.5 ticks of a normal simulation.
What do you think should be the speed (ticks per second) of the simulation for everything to run smoothly?

As a rule, some of the behavior is optimized due to the fact that the input has a delay. For example, you press to create a soldier and he is placed on the field in 1s. Thus, with a delay of 0.5s, we simply put a soldier whose timer is immediately 0.5s (1-0.5)
And we don't need to resimulate the entire state.

**Comment by chromealex** [comment]
Have you check an example repo? There is an old version of ecs, but it
works and you can find it interesting to research.

Input markers are decoded into events, thats resimulating when you are
receiving these events from network.

Resimulation works tick-by-tick, so I think tick time should be as large as
possible (may be 100ms in a good way, but depends on the game mechanics).
In our projects we use 33ms as a tick time, so it will run smoothly because
your logic must fit 33ms (if you will get 20 ticks of rollback - it must
fit 33/20=1.65ms per tick).

You can control “input delay”, so you can pick any delay you want to use in
your game, all events will fire with this delay and net latency factor
could be minimized then.

**Comment by echeg** [comment]
I check this repo. Maybe I looked bad.

If I understood you correctly. That's the formula:
resumulation speed = one tick time / max count rollback ticks

You can control “input delay” - how?

What happens if the delay is greater than the maximum rollback length?

**Comment by chromealex** [comment]
In ME.ECS you have a “reset state” which has tick = 0, so if you have a
very old event - this state will be used to rollback.
In your HistoryStatesModule you can set 2 values - states capacity and
frequency - so these values allow you to choose history length.
Input delay - it is an method override in network module, check the
override methods.
Resimulation time = resimulation ticks count * avg logic time per tick

**Comment by echeg** [comment]
I didn’t put it exactly.
"resumulation speed = one tick time / max count rollback ticks"
I meant that in order for resimulation to work smoothly, it must be faster than 1 tick, as many times as the depth of resimulation.

If we have smooth gameplay then we should simulate at least 20 ticks in one second. those. logical tick 1/20 = 0.05s
And if we want to restimulate 0.5s it will be 10 ticks. For the resimulation to be smooth, it is desirable that it be calculated for 1tik? total comes out 0.05s / 10 = 5ms. If we want rollbacks for 1 second, it will already be 2.5ms
At the same time, do not forget that at this time all other logic, interfaces and effects continue to work.
I've seen this approach work for fighting games, with a 60 tick (1s) ringbuffer. But the fighting game has very easy logic.
I'm trying to understand how the option with resimulation is possible if we are talking about a battler with 20 heroes. 
I saw and wrote several butlers and the best thing was that the logic worked in ~4ms


"Input delay - it is an method override in network module, check the
override methods."  
I tried to search for "delay" but found references only in inside lag simulation inside photon.
Maybe it's called something different? i read the whole NetworkModule\NetworkModule.cs and exnampe\modules\networkmodule

**Comment by chromealex** [comment]
GetTicksForInput

This method inside NetworkModule

We are using this system in the game with 4k units and it's run in 30fps on
mobile devices.
You are right about simulation time and it is true, but in general in
ME.ECS one tick logic fits in 1ms or so.
We are using 0.033secs per tick, so it's 30fps. So your resimulation must
fit in 33ms per frame to run smoothly. So 33ms/20 ticks = 1.65ms per tick
max to run smoothly (where 20 ticks = 20 * 33ms = 660ms ping).

вт, 11 мая 2021 г. в 15:18, Evgeniy Chegodaev ***@***.***>:

**Comment by echeg** [comment]
> GetTicksForInput This method inside NetworkModule

In this repo no method "GetTicksForInput"  and submodule use old version ecs without this.

In https://github.com/chromealex/ecs-submodule i found "GetTicksForInput" in ECS/Modules/StatesHistoryModule/StatesHistoryModule.cs

And usage this.statesHistoryModule.GetEventForwardTick(); in NetworkModule
Thanks, I think I figured out how it works.

As far as I understand, I can use custom tick "offest". And for example, for one type of input, make a delay of 0.5s(10 ticks), and for another 1s (20 ticks). For optimization. 

The only thing, for example, to start showing the spawn animation, is desirable for me to handle this event as soon as it arrives. And do not wait for the tick when the unit should already appear.

**Comment by chromealex** [comment]
If you want to start animation immediately you dont need to change
GetTicksForInput.
First of all, just try to build your game with 0.033secs as a tick time,
then when you got some results - you can check profiler and check
performance.
